name: Website Health Check

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  ping-website:
    runs-on: ubuntu-latest

    steps:
      - name: Send request to portfolio
        run: |
          curl -fsS --max-time 30 \
            https://rohaanzahid.space/ \
            -o /dev/null
